# Use the official Python image
FROM python:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the source code into the container
COPY . .

# Specify the command to run the Python script
CMD ["pwd"]
# CMD ["python3", "python_socket_server.py"]
