// This file is automatically generated by build.rs
// Do not edit this file manually!

use horizon_plugin_api::{Pluginstate, LoadedPlugin, Plugin};
use std::collections::HashMap;

pub use chronos_plugin;
pub use player_lib;
pub use stars_beyond_plugin;
pub use unreal_adapter_horizon;


// Invoke the macro with all discovered plugins
pub fn load_plugins() -> HashMap<String, (Pluginstate, Plugin)> {
    let plugins = crate::load_plugins!(
        chronos_plugin,
        player_lib,
        stars_beyond_plugin,
        unreal_adapter_horizon
    );
    plugins
}
