// This file is automatically generated by build.rs
// Do not edit manually!

use horizon_plugin_api::Plugin;

use test_plugin;
use test_plugin::Plugin_API;


pub struct LoadedPlugin {
    pub name: &'static str,
    pub instance: Plugin,
}

pub fn load_plugins() -> Vec<LoadedPlugin> {
    vec![
        LoadedPlugin {
            name: "test_plugin",
            instance: test_plugin::Plugin::new(),
        },
    ]
}
